export const SET_ALBUMS = 'SET_ALBUMS';

export const GET_ALBUMS_STARTED = 'GET_ALBUMS_STARTED';
export const GET_ALBUMS_SUCCESS = 'GET_ALBUMS_SUCCESS';
export const GET_ALBUMS_FAILURE = 'GET_ALBUMS_FAILURE';

export const ADD_ALBUM_STARTED = 'ADD_ALBUM_STARTED';
export const ADD_ALBUM_SUCCESS = 'ADD_ALBUM_SUCCESS';
export const ADD_ALBUM_FAILURE = 'ADD_ALBUM_FAILURE';

export const GET_ALBUM_PHOTOS_STARTED = 'GET_ALBUM_PHOTOS_STARTED';
export const GET_ALBUM_PHOTOS_SUCCESS = 'GET_ALBUM_PHOTOS_SUCCESS';
export const GET_ALBUM_PHOTOS_FAILURE = 'GET_ALBUM_PHOTOS_FAILURE';

export const SET_ACTIVE_ALBUM = 'SET_ACTIVE_ALBUM';
